# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hack4no' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	pod 'SwiftyJSON'
	pod 'Alamofire'
	pod 'AlamofireNetworkActivityIndicator'

  target 'hack4noTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hack4noUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
